### ISSUE TITLE
hash collision

### ISSUE THREAD

**Issue by arianne-detorres** [10cella/hashids-java#68]
Hi, I'm using hashids to encode internal ids in our system, however I noticed a few collisions: 

```
Hashids hashids = new Hashids( salt, 8, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890" );
System.out.println(hashids.encode( 5551008 ));
System.out.println(hashids.encode( 5552196 ));
```

Returns:
```
mnbgLzGm
mnbgLZGm
```

Any ideas as to how this can happen? From the documentation, it seems this should be impossible.  We're using the latest version (1.0.3)

**Comment by 0x3333** [comment]
Same as issue #62 . Letter Z in upper, and lower case. Hashids are case sensitive.
