### ISSUE TITLE
Human Readable UUID

### ISSUE THREAD

**Issue by mohanr** [10cella/hashids-java#71]
`Hashids hashids = new Hashids("this is my salt");
        String id = hashids.encodeHex("586e8cc62663421eadf9d4efa2bd19f4");`

This gives `yNZEZnb9oDTmEvJpLDqxhw9MQeZ`. Can it be shorter at all ?

**Comment by 0x3333** [comment]
Plain simple, no. 😉 You can reduce the number, you will reduce the output.
